project_id = "ipxgoqpkbgyijfubqaqi"

[functions.admin-user-actions]
verify_jwt = false

[functions.fetch-crypto-prices]
verify_jwt = false

[functions.oxapay-create-invoice]
verify_jwt = true

[functions.oxapay-webhook]
verify_jwt = false

[functions.oxapay-check-status]
verify_jwt = true
